### ISSUE TITLE
-std=c++11 error while compiling

### ISSUE THREAD

**Issue by debidatta** [taketwo/tcs#1]
While compiling the following error occurs

```
 ~/tcs/tcs$ make
[  3%] Building CXX object CMakeFiles/io.dir/src/io.cpp.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
```

I thought it was because I was running gcc version 4.6. I tried to upgrade it to 4.7 but that results in an internal compiler error.

**Comment by taketwo** [comment]
gcc 4.6 has a limited support for c++11. In fact, at the time 4.6 was released the standard was still a draft and hence the corresponding command line option was `-std=c++0x`.

But anyways, 4.6 does not implement all the features needed to compile this project. I think 4.7 should be sufficient because it implements the standard [almost completely](http://gcc.gnu.org/gcc-4.7/cxx0x_status.html). However I have never tried to compile with 4.7 because I have 4.8.1 on my machine.

Could you paste the internal compiler error you are getting with 4.7?

**Comment by debidatta** [comment]
Okay. The error log for internal compiler error gets dumped into a huge file. If you want I can send it to you. The message shown is `Internal compiler error: Error reporting routines re-entered.`This is preceded by lots of errors of using deleted functions in Boost. So I am trying to update Boost and use gcc-4.8

**Comment by taketwo** [comment]
I suspect boost causes trouble. You absolutely need boost 1.53. Earlier versions won't work, this I know for sure.

Please update boost and if the problem remains send me the log. Also do not forget to update eigen to 3.2.

**Comment by taketwo** [comment]
... and yes, I know this is a lot of dependencies, but on the brighter side, they all are satisfied in e.g. Ubuntu 13.10.

**Comment by debidatta** [comment]
Yes. Boost seems to be the culprit. But currently, I am on ubuntu 12.04 now which does not have libboost1.53 in aptitude for it. I'll see if I can get a machine on which I can upgrade ubuntu. Thanks.

**Comment by taketwo** [comment]
You can easily get the required versions of boost and eigen even on 12.04. Just add

```
sudo add-apt-repository ppa:apokluda/boost1.53
```

for boost and

```
sudo add-apt-repository ppa:yade-users/external
```

for eigen. Then after

```
sudo apt-get update -d
```

you can install boost 1.53 and eigen 3.2 with

```
sudo apt-get install libeigen3-dev libboost1.53-dev
```

This is how we get these libraries on Travis which also runs 12.04 LTS.

**Comment by debidatta** [comment]
Thanks for the links to the PPA. I followed up by installing libboost1.53-dev which required me to remove libpcl which I thought can be built again after installing that. 

I also did this 
`sudo apt-get install libboost1.53-all-dev`
which ends up installing only 

```
/usr/lib/libboost_atomic.so          /usr/lib/libboost_iostreams.so  /usr/lib/libboost_math_tr1.so          /usr/lib/libboost_python-py27.so    /usr/lib/libboost_system.so
/usr/lib/libboost_chrono.so          /usr/lib/libboost_locale.so     /usr/lib/libboost_mpi_python-py27.so   /usr/lib/libboost_python-py32.so    /usr/lib/libboost_thread.so
/usr/lib/libboost_context.so         /usr/lib/libboost_math_c99f.so  /usr/lib/libboost_mpi_python-py32.so   /usr/lib/libboost_python.so         /usr/lib/libboost_timer.so
/usr/lib/libboost_date_time.so       /usr/lib/libboost_math_c99l.so  /usr/lib/libboost_mpi_python.so        /usr/lib/libboost_random.so         /usr/lib/libboost_unit_test_framework.so
/usr/lib/libboost_filesystem.so      /usr/lib/libboost_math_c99.so   /usr/lib/libboost_mpi.so               /usr/lib/libboost_regex.so          /usr/lib/libboost_wave.so
/usr/lib/libboost_graph_parallel.so  /usr/lib/libboost_math_tr1f.so  /usr/lib/libboost_prg_exec_monitor.so  /usr/lib/libboost_serialization.so  /usr/lib/libboost_wserialization.so
/usr/lib/libboost_graph.so           /usr/lib/libboost_math_tr1l.so  /usr/lib/libboost_program_options.so   /usr/lib/libboost_signals.so
```

As some libbooost libraries are missing I get the following error 

```
No rule to make target `/usr/lib/libboost_system-mt.so', needed by `lib/libpcl_common.so.1.7.1'.  Stop.
```

**Comment by taketwo** [comment]
Hmm, that's strange. Here is how boost is installed on Travis (excerpt from PCL's [.travis.yml](https://github.com/PointCloudLibrary/pcl/blob/master/.travis.yml)):

```
before_install:
  - sudo add-apt-repository ppa:apokluda/boost1.53 -y
  - sudo apt-get update -d
install:
  - sudo apt-get install libboost-filesystem1.53-dev libboost-iostreams1.53-dev libboost-thread1.53-dev
```

As I mentioned, Travis runs 12.04, so it has the same boost version as you by default. And then it seems like we are installing only several boost modules from 1.53 release.

**Comment by taketwo** [comment]
In fact, my code only needs a fresh version of Boost Graph Library. So perhaps it could be sufficient to install just `libboost-graph1.53-dev` (if it exists).

**Comment by debidatta** [comment]
Yes that is strange. libboost-system-mt.so doesn't seems to be available for install also. Let me revert to a n older boost and only update the libboost-graph library

**Comment by debidatta** [comment]
It is not possible to only install the graph library of libboost1.53 . It requires all the other packages to be upgraded and in 1.53 libboost-system-mt is missing which is required to make libpcl-common

**Comment by taketwo** [comment]
What about this PPA? https://launchpad.net/~boost-latest/+archive/ppa
Maybe it includes all boost modules.
